fail_fast: true
default_install_hook_types:
- pre-commit
- pre-push
default_stages:
- pre-commit

repos:
- repo: 'https://github.com/pre-commit/pre-commit-hooks'
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
    stages: [pre-commit]
  - id: check-yaml

- repo: local
  hooks:
  - id: go-build
    name: go build
    language: system
    pass_filenames: false
    stages: [pre-commit]
    entry: go build

  # - id: go-generate
  #   name: go generate
  #   entry: go generate ./...
  #   files: '\.go$'
  #   language: system
  #   pass_filenames: false

  - id: go-test
    name: gotestsum
    entry: gotestsum -f dots -- -failfast ./...
    files: '\.go$'
    language: system
    pass_filenames: false
    stages: [pre-push]
