bot_secret: 'sample'  # replace or overwrite by setting BOT_SECRET in env vars!
database_dsn: 'postgres://username:password@host:port/database'
enable_debug: false
cogs:
  general:
    motd: "Don't forget to drink water!"
    repo_name: "GitHub · fiffu/arisa2"
    repo_web_url: "https://github.com/fiffu/arisa3"
    repo_issues_url: "https://github.com/fiffu/arisa3/issues"
    repo_gitclone_url: "https://github.com/fiffu/arisa3.git"
  colours:
    max_role_height_name: "[Arisa] Max colour role height"
    mutate_cooldown_mins: 240
    reroll_cooldown_mins: 720
    reroll_penalty_mins: 30
  cardboard:
    user: username
    api_key: apikey
