// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package api is a generated GoMock package.
package api

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIClient is a mock of IClient interface.
type MockIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIClientMockRecorder
}

// MockIClientMockRecorder is the mock recorder for MockIClient.
type MockIClientMockRecorder struct {
	mock *MockIClient
}

// NewMockIClient creates a new mock instance.
func NewMockIClient(ctrl *gomock.Controller) *MockIClient {
	mock := &MockIClient{ctrl: ctrl}
	mock.recorder = &MockIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClient) EXPECT() *MockIClientMockRecorder {
	return m.recorder
}

// AutocompleteTag mocks base method.
func (m *MockIClient) AutocompleteTag(ctx context.Context, query string) ([]*TagSuggestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutocompleteTag", ctx, query)
	ret0, _ := ret[0].([]*TagSuggestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AutocompleteTag indicates an expected call of AutocompleteTag.
func (mr *MockIClientMockRecorder) AutocompleteTag(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutocompleteTag", reflect.TypeOf((*MockIClient)(nil).AutocompleteTag), ctx, query)
}

// FaviconURL mocks base method.
func (m *MockIClient) FaviconURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FaviconURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// FaviconURL indicates an expected call of FaviconURL.
func (mr *MockIClientMockRecorder) FaviconURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FaviconURL", reflect.TypeOf((*MockIClient)(nil).FaviconURL))
}

// GetPosts mocks base method.
func (m *MockIClient) GetPosts(ctx context.Context, tags []string) ([]*Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPosts", ctx, tags)
	ret0, _ := ret[0].([]*Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPosts indicates an expected call of GetPosts.
func (mr *MockIClientMockRecorder) GetPosts(ctx, tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPosts", reflect.TypeOf((*MockIClient)(nil).GetPosts), ctx, tags)
}

// GetTags mocks base method.
func (m *MockIClient) GetTags(ctx context.Context, tags []string) (map[string]*Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTags", ctx, tags)
	ret0, _ := ret[0].(map[string]*Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTags indicates an expected call of GetTags.
func (mr *MockIClientMockRecorder) GetTags(ctx, tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTags", reflect.TypeOf((*MockIClient)(nil).GetTags), ctx, tags)
}

// GetTagsMatching mocks base method.
func (m *MockIClient) GetTagsMatching(ctx context.Context, pattern string) ([]*Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagsMatching", ctx, pattern)
	ret0, _ := ret[0].([]*Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagsMatching indicates an expected call of GetTagsMatching.
func (mr *MockIClientMockRecorder) GetTagsMatching(ctx, pattern interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagsMatching", reflect.TypeOf((*MockIClient)(nil).GetTagsMatching), ctx, pattern)
}

// UseAuth mocks base method.
func (m *MockIClient) UseAuth() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UseAuth")
	ret0, _ := ret[0].(bool)
	return ret0
}

// UseAuth indicates an expected call of UseAuth.
func (mr *MockIClientMockRecorder) UseAuth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseAuth", reflect.TypeOf((*MockIClient)(nil).UseAuth))
}
